### ISSUE TITLE
How to put Large image?

### ISSUE THREAD

**Issue by friostd** [JasonBenfrin/Discord-Rich-Presence-Android#10]
When I put the url of the Large image it doesn't work.

![Screenshot_20220925_184558](https://user-images.githubusercontent.com/87456223/192166980-39e0afb0-d044-481e-bf28-ada7f8553166.jpg)

**Comment by JasonBenfrin** [comment]
It has to be an image that is already uploaded to Discord

**Comment by redentdev** [comment]
how can i use this assets from developer portal in my presence?

![Screenshot_20221001-094031.png](https://user-images.githubusercontent.com/74617921/193396434-9f2bfacd-ee0c-4fd4-81bc-450be0b0777c.png)

**Comment by JasonBenfrin** [comment]
You can get the image url in developer tools. If you are on desktop press Crtl+Shift+C and click on the picture.
It will highlight an element on the right side and you will able to find it's url in the element
