### ISSUE TITLE
Feature request: add an option to display currently playing music

### ISSUE THREAD

**Issue by dgudim** [JasonBenfrin/Discord-Rich-Presence-Android#11]
It would be nice to have spotify-like rich presence but for any music player, something like [this](https://github.com/FichteFoll/discordrp-mpris)

**Comment by JasonBenfrin** [comment]
I wouldn't recommend you using my app since there is already an app made by Kizzy [here](https://github.com/dead8309/Kizzy/releases/tag/3.6). It's called Media RPC in there

**Comment by JasonBenfrin** [comment]
To be honest I've already planned to archive this project but I also want to migrate to React or Flutter but I couldn't find time to do so not much updates will be put here

**Comment by dgudim** [comment]
Please don't go the React route, other than that, Kizzy looks like exactly what I wanted, thanks. And also, good luck.
