### ISSUE TITLE
Cant get it to get my token

### ISSUE THREAD

**Issue by Awesomeless19** [JasonBenfrin/Discord-Rich-Presence-Android#12]
I log in, and then it says unable to get token. I will close it and reopen it it says logged in, and then when I do everything it doesn't work. But if I use an ALT account, that works. I don't know what the problem is, someone please help.

**Comment by JasonBenfrin** [comment]
Yeah I'm very aware of that it's a bug, when things don't work, log out and log in again. I don't have much time to fix the bug so that's the only solution I have. If nothing works, just clear the data of the app or reinstall it again.

**Comment by Awesomeless19** [comment]
Thanks for telling me it's very prominent. I'll try your advice and other stuff. Thanks for your help
