### ISSUE TITLE
Button URL

### ISSUE THREAD

**Issue by redentdev** [JasonBenfrin/Discord-Rich-Presence-Android#5]
Where do I write the button link?!

![Screenshot_2022-06-27-18-05-28.png](https://user-images.githubusercontent.com/74617921/175972940-86837df5-d097-4311-967c-4571eb2e9c39.png)

**Comment by JasonBenfrin** [comment]
Currently you cannot put links in buttons. The documentation says it should work but it doesn't.

**Comment by JasonBenfrin** [comment]
Kizzy found a way to add URL! Woohoo

**Comment by redentdev** [comment]
> Kizzy found a way to add URL! Woohoo

if you do, when will you publish it?

**Comment by JasonBenfrin** [comment]
> if you do, when will you publish it?

If I can finish it tomorrow I might publish it tomorrow.

**Comment by redentdev** [comment]
> > if you do, when will you publish it?
> 
> If I can finish it tomorrow I might publish it tomorrow.

okey thanks

**Comment by JasonBenfrin** [comment]
Added in 53597841a18dd99a7c16c271baa8f7e24a3173e2
