### ISSUE TITLE
What are flags

### ISSUE THREAD

**Issue by redentdev** [JasonBenfrin/Discord-Rich-Presence-Android#7]
Can you tell me what the flags are?

**Comment by JasonBenfrin** [comment]
Activity Flags describe what the activity payload includes. [List of Flags.](https://discord.com/developers/docs/topics/gateway#activity-object-activity-flags)
They are integer values between 1 and 510. The way you calculate the bits is simple, let's say you want the Embedded flag and Play flag.
From the table:
| Name | Value | Result |
|  ---  |  --- | --- |
|  EMBEDDED  |  1 << 8  |  256 |
|  PLAY  |  1 << 5  | 32 |

 _<< is called a Left-Shift operator. More about them [here.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Left_shift#description)_

When we add those two numbers, 256 and 32, we get 288 and that's the number what we put in.

### Is this really useful for us?

Yes, by adding flags, we can disguise as Spotify _( Spotify uses flags of 48 )_
The Flag Embedded is especially useful.
If you add 256 to the flags, The Playing, Listening texts will be gone and only the Name is shown.

I hope this is helpful.
