### ISSUE TITLE
Cant add images (or at least not how I tried it)

### ISSUE THREAD

**Issue by Cryptabey** [JasonBenfrin/Discord-Rich-Presence-Android#8]
Hi I have tried putting in images and it doesnt seem to work whenever I put in the url it doesnt appear in the discord app I verified the images are squared and I also tried hosting them on imgbb and it still doesnt work so I would like to know how to put in those images (do I need to host on an other website maybe? Or maybe this has to do with the application id?)

**Comment by JasonBenfrin** [comment]
You can't use external images outside of Discord. First, you must upload your image to Discord ( eg. upload it to your private server ). Then copy the full URL and then paste it into the app.

**Comment by JasonBenfrin** [comment]
> You can't use external images outside of Discord.

By this, I meant external images except Spotify and Samsung Store
